# coding: utf-8

# flake8: noqa
"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.activity_dto import ActivityDto
from swagger_client.models.admission_criteria_dto import AdmissionCriteriaDto
from swagger_client.models.admission_rule_dto import AdmissionRuleDto
from swagger_client.models.admission_status_dto import AdmissionStatusDto
from swagger_client.models.assessment_allocation_dto import AssessmentAllocationDto
from swagger_client.models.assessment_create_dto import AssessmentCreateDto
from swagger_client.models.assessment_dto import AssessmentDto
from swagger_client.models.assessment_event_dto import AssessmentEventDto
from swagger_client.models.assessment_update_dto import AssessmentUpdateDto
from swagger_client.models.assignment_dto import AssignmentDto
from swagger_client.models.assignment_group_tuple import AssignmentGroupTuple
from swagger_client.models.assignment_update_dto import AssignmentUpdateDto
from swagger_client.models.auth_result_dto import AuthResultDto
from swagger_client.models.can_join_course_dto import CanJoinCourseDto
from swagger_client.models.change_course_role_dto import ChangeCourseRoleDto
from swagger_client.models.course_about_dto import CourseAboutDto
from swagger_client.models.course_config_dto import CourseConfigDto
from swagger_client.models.course_config_update_dto import CourseConfigUpdateDto
from swagger_client.models.course_create_dto import CourseCreateDto
from swagger_client.models.course_dto import CourseDto
from swagger_client.models.credentials_dto import CredentialsDto
from swagger_client.models.group_create_bulk_dto import GroupCreateBulkDto
from swagger_client.models.group_dto import GroupDto
from swagger_client.models.group_event_dto import GroupEventDto
from swagger_client.models.group_settings_dto import GroupSettingsDto
from swagger_client.models.group_settings_update_dto import GroupSettingsUpdateDto
from swagger_client.models.group_update_dto import GroupUpdateDto
from swagger_client.models.group_with_assigned_evaluator_dto import GroupWithAssignedEvaluatorDto
from swagger_client.models.individual_percent_with_allowed_failures_rule_dto import IndividualPercentWithAllowedFailuresRuleDto
from swagger_client.models.link_dto import LinkDto
from swagger_client.models.marker_dto import MarkerDto
from swagger_client.models.notification_dto import NotificationDto
from swagger_client.models.overall_percent_rule_dto import OverallPercentRuleDto
from swagger_client.models.partial_assessment_dto import PartialAssessmentDto
from swagger_client.models.participant_dto import ParticipantDto
from swagger_client.models.participants_comparison_dto import ParticipantsComparisonDto
from swagger_client.models.participants_with_assigned_evaluator_dto import ParticipantsWithAssignedEvaluatorDto
from swagger_client.models.password_dto import PasswordDto
from swagger_client.models.pick_type_class import PickTypeClass
from swagger_client.models.points_overview_dto import PointsOverviewDto
from swagger_client.models.r_export_admission_status import RExportAdmissionStatus
from swagger_client.models.r_export_dto import RExportDto
from swagger_client.models.r_export_grade import RExportGrade
from swagger_client.models.r_export_group import RExportGroup
from swagger_client.models.r_export_registered_groups import RExportRegisteredGroups
from swagger_client.models.r_export_student import RExportStudent
from swagger_client.models.r_export_submission import RExportSubmission
from swagger_client.models.r_export_user_info import RExportUserInfo
from swagger_client.models.rounding_behavior import RoundingBehavior
from swagger_client.models.rule_check_result import RuleCheckResult
from swagger_client.models.student_mgmt_event import StudentMgmtEvent
from swagger_client.models.student_mgmt_exception import StudentMgmtException
from swagger_client.models.student_results import StudentResults
from swagger_client.models.submission_config_dto import SubmissionConfigDto
from swagger_client.models.submission_create_dto import SubmissionCreateDto
from swagger_client.models.submission_dto import SubmissionDto
from swagger_client.models.subscriber_dto import SubscriberDto
from swagger_client.models.user_dto import UserDto
from swagger_client.models.user_settings_dto import UserSettingsDto
from swagger_client.models.user_update_dto import UserUpdateDto
