# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssessmentEventDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assessment_id': 'str',
        'user_id': 'str',
        'user': 'UserDto',
        'event': 'str',
        'timestamp': 'datetime',
        'payload': 'object'
    }

    attribute_map = {
        'assessment_id': 'assessmentId',
        'user_id': 'userId',
        'user': 'user',
        'event': 'event',
        'timestamp': 'timestamp',
        'payload': 'payload'
    }

    def __init__(self, assessment_id=None, user_id=None, user=None, event=None, timestamp=None, payload=None):  # noqa: E501
        """AssessmentEventDto - a model defined in Swagger"""  # noqa: E501
        self._assessment_id = None
        self._user_id = None
        self._user = None
        self._event = None
        self._timestamp = None
        self._payload = None
        self.discriminator = None
        self.assessment_id = assessment_id
        self.user_id = user_id
        self.user = user
        self.event = event
        self.timestamp = timestamp
        if payload is not None:
            self.payload = payload

    @property
    def assessment_id(self):
        """Gets the assessment_id of this AssessmentEventDto.  # noqa: E501


        :return: The assessment_id of this AssessmentEventDto.  # noqa: E501
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """Sets the assessment_id of this AssessmentEventDto.


        :param assessment_id: The assessment_id of this AssessmentEventDto.  # noqa: E501
        :type: str
        """
        if assessment_id is None:
            raise ValueError("Invalid value for `assessment_id`, must not be `None`")  # noqa: E501

        self._assessment_id = assessment_id

    @property
    def user_id(self):
        """Gets the user_id of this AssessmentEventDto.  # noqa: E501


        :return: The user_id of this AssessmentEventDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AssessmentEventDto.


        :param user_id: The user_id of this AssessmentEventDto.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def user(self):
        """Gets the user of this AssessmentEventDto.  # noqa: E501


        :return: The user of this AssessmentEventDto.  # noqa: E501
        :rtype: UserDto
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AssessmentEventDto.


        :param user: The user of this AssessmentEventDto.  # noqa: E501
        :type: UserDto
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def event(self):
        """Gets the event of this AssessmentEventDto.  # noqa: E501


        :return: The event of this AssessmentEventDto.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this AssessmentEventDto.


        :param event: The event of this AssessmentEventDto.  # noqa: E501
        :type: str
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501

        self._event = event

    @property
    def timestamp(self):
        """Gets the timestamp of this AssessmentEventDto.  # noqa: E501


        :return: The timestamp of this AssessmentEventDto.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this AssessmentEventDto.


        :param timestamp: The timestamp of this AssessmentEventDto.  # noqa: E501
        :type: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def payload(self):
        """Gets the payload of this AssessmentEventDto.  # noqa: E501


        :return: The payload of this AssessmentEventDto.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this AssessmentEventDto.


        :param payload: The payload of this AssessmentEventDto.  # noqa: E501
        :type: object
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssessmentEventDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssessmentEventDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
