# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssessmentCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assignment_id': 'str',
        'is_draft': 'bool',
        'achieved_points': 'float',
        'comment': 'str',
        'group_id': 'str',
        'user_id': 'str',
        'partial_assessments': 'list[PartialAssessmentDto]'
    }

    attribute_map = {
        'assignment_id': 'assignmentId',
        'is_draft': 'isDraft',
        'achieved_points': 'achievedPoints',
        'comment': 'comment',
        'group_id': 'groupId',
        'user_id': 'userId',
        'partial_assessments': 'partialAssessments'
    }

    def __init__(self, assignment_id=None, is_draft=None, achieved_points=None, comment=None, group_id=None, user_id=None, partial_assessments=None):  # noqa: E501
        """AssessmentCreateDto - a model defined in Swagger"""  # noqa: E501
        self._assignment_id = None
        self._is_draft = None
        self._achieved_points = None
        self._comment = None
        self._group_id = None
        self._user_id = None
        self._partial_assessments = None
        self.discriminator = None
        self.assignment_id = assignment_id
        self.is_draft = is_draft
        if achieved_points is not None:
            self.achieved_points = achieved_points
        if comment is not None:
            self.comment = comment
        if group_id is not None:
            self.group_id = group_id
        if user_id is not None:
            self.user_id = user_id
        if partial_assessments is not None:
            self.partial_assessments = partial_assessments

    @property
    def assignment_id(self):
        """Gets the assignment_id of this AssessmentCreateDto.  # noqa: E501

        Identifier of the assignment that is being evaluated by this assessment.  # noqa: E501

        :return: The assignment_id of this AssessmentCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._assignment_id

    @assignment_id.setter
    def assignment_id(self, assignment_id):
        """Sets the assignment_id of this AssessmentCreateDto.

        Identifier of the assignment that is being evaluated by this assessment.  # noqa: E501

        :param assignment_id: The assignment_id of this AssessmentCreateDto.  # noqa: E501
        :type: str
        """
        if assignment_id is None:
            raise ValueError("Invalid value for `assignment_id`, must not be `None`")  # noqa: E501

        self._assignment_id = assignment_id

    @property
    def is_draft(self):
        """Gets the is_draft of this AssessmentCreateDto.  # noqa: E501

        Marks the assessment as a draft.  # noqa: E501

        :return: The is_draft of this AssessmentCreateDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_draft

    @is_draft.setter
    def is_draft(self, is_draft):
        """Sets the is_draft of this AssessmentCreateDto.

        Marks the assessment as a draft.  # noqa: E501

        :param is_draft: The is_draft of this AssessmentCreateDto.  # noqa: E501
        :type: bool
        """
        if is_draft is None:
            raise ValueError("Invalid value for `is_draft`, must not be `None`")  # noqa: E501

        self._is_draft = is_draft

    @property
    def achieved_points(self):
        """Gets the achieved_points of this AssessmentCreateDto.  # noqa: E501

        The amount of points that the student or group achieved with their submission.  # noqa: E501

        :return: The achieved_points of this AssessmentCreateDto.  # noqa: E501
        :rtype: float
        """
        return self._achieved_points

    @achieved_points.setter
    def achieved_points(self, achieved_points):
        """Sets the achieved_points of this AssessmentCreateDto.

        The amount of points that the student or group achieved with their submission.  # noqa: E501

        :param achieved_points: The achieved_points of this AssessmentCreateDto.  # noqa: E501
        :type: float
        """

        self._achieved_points = achieved_points

    @property
    def comment(self):
        """Gets the comment of this AssessmentCreateDto.  # noqa: E501

        A comment providing additional feedback.  # noqa: E501

        :return: The comment of this AssessmentCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this AssessmentCreateDto.

        A comment providing additional feedback.  # noqa: E501

        :param comment: The comment of this AssessmentCreateDto.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def group_id(self):
        """Gets the group_id of this AssessmentCreateDto.  # noqa: E501

        If a group submission is being evaluated, contains the identifier of the group.  # noqa: E501

        :return: The group_id of this AssessmentCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this AssessmentCreateDto.

        If a group submission is being evaluated, contains the identifier of the group.  # noqa: E501

        :param group_id: The group_id of this AssessmentCreateDto.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def user_id(self):
        """Gets the user_id of this AssessmentCreateDto.  # noqa: E501

        If a single user is being evaluated, contains the identifier of the user.  # noqa: E501

        :return: The user_id of this AssessmentCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AssessmentCreateDto.

        If a single user is being evaluated, contains the identifier of the user.  # noqa: E501

        :param user_id: The user_id of this AssessmentCreateDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def partial_assessments(self):
        """Gets the partial_assessments of this AssessmentCreateDto.  # noqa: E501


        :return: The partial_assessments of this AssessmentCreateDto.  # noqa: E501
        :rtype: list[PartialAssessmentDto]
        """
        return self._partial_assessments

    @partial_assessments.setter
    def partial_assessments(self, partial_assessments):
        """Sets the partial_assessments of this AssessmentCreateDto.


        :param partial_assessments: The partial_assessments of this AssessmentCreateDto.  # noqa: E501
        :type: list[PartialAssessmentDto]
        """

        self._partial_assessments = partial_assessments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssessmentCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssessmentCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
