# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssessmentAllocationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assigned_evaluator_id': 'str',
        'group_id': 'str',
        'user_id': 'str',
        'assignment_id': 'str'
    }

    attribute_map = {
        'assigned_evaluator_id': 'assignedEvaluatorId',
        'group_id': 'groupId',
        'user_id': 'userId',
        'assignment_id': 'assignmentId'
    }

    def __init__(self, assigned_evaluator_id=None, group_id=None, user_id=None, assignment_id=None):  # noqa: E501
        """AssessmentAllocationDto - a model defined in Swagger"""  # noqa: E501
        self._assigned_evaluator_id = None
        self._group_id = None
        self._user_id = None
        self._assignment_id = None
        self.discriminator = None
        self.assigned_evaluator_id = assigned_evaluator_id
        if group_id is not None:
            self.group_id = group_id
        if user_id is not None:
            self.user_id = user_id
        self.assignment_id = assignment_id

    @property
    def assigned_evaluator_id(self):
        """Gets the assigned_evaluator_id of this AssessmentAllocationDto.  # noqa: E501

        UserId of the assigned evaluator.  # noqa: E501

        :return: The assigned_evaluator_id of this AssessmentAllocationDto.  # noqa: E501
        :rtype: str
        """
        return self._assigned_evaluator_id

    @assigned_evaluator_id.setter
    def assigned_evaluator_id(self, assigned_evaluator_id):
        """Sets the assigned_evaluator_id of this AssessmentAllocationDto.

        UserId of the assigned evaluator.  # noqa: E501

        :param assigned_evaluator_id: The assigned_evaluator_id of this AssessmentAllocationDto.  # noqa: E501
        :type: str
        """
        if assigned_evaluator_id is None:
            raise ValueError("Invalid value for `assigned_evaluator_id`, must not be `None`")  # noqa: E501

        self._assigned_evaluator_id = assigned_evaluator_id

    @property
    def group_id(self):
        """Gets the group_id of this AssessmentAllocationDto.  # noqa: E501

        GroupId of the group, whose solution should be evaluated by the assigned evaluator.  # noqa: E501

        :return: The group_id of this AssessmentAllocationDto.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this AssessmentAllocationDto.

        GroupId of the group, whose solution should be evaluated by the assigned evaluator.  # noqa: E501

        :param group_id: The group_id of this AssessmentAllocationDto.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def user_id(self):
        """Gets the user_id of this AssessmentAllocationDto.  # noqa: E501

        UserId of the user, whose solution should be evaluated by the assigned evaluator.  # noqa: E501

        :return: The user_id of this AssessmentAllocationDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AssessmentAllocationDto.

        UserId of the user, whose solution should be evaluated by the assigned evaluator.  # noqa: E501

        :param user_id: The user_id of this AssessmentAllocationDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def assignment_id(self):
        """Gets the assignment_id of this AssessmentAllocationDto.  # noqa: E501


        :return: The assignment_id of this AssessmentAllocationDto.  # noqa: E501
        :rtype: str
        """
        return self._assignment_id

    @assignment_id.setter
    def assignment_id(self, assignment_id):
        """Sets the assignment_id of this AssessmentAllocationDto.


        :param assignment_id: The assignment_id of this AssessmentAllocationDto.  # noqa: E501
        :type: str
        """
        if assignment_id is None:
            raise ValueError("Invalid value for `assignment_id`, must not be `None`")  # noqa: E501

        self._assignment_id = assignment_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssessmentAllocationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssessmentAllocationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
