# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupWithAssignedEvaluatorDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assigned_evaluator_id': 'str',
        'assessment_id': 'str',
        'group': 'GroupDto'
    }

    attribute_map = {
        'assigned_evaluator_id': 'assignedEvaluatorId',
        'assessment_id': 'assessmentId',
        'group': 'group'
    }

    def __init__(self, assigned_evaluator_id=None, assessment_id=None, group=None):  # noqa: E501
        """GroupWithAssignedEvaluatorDto - a model defined in Swagger"""  # noqa: E501
        self._assigned_evaluator_id = None
        self._assessment_id = None
        self._group = None
        self.discriminator = None
        if assigned_evaluator_id is not None:
            self.assigned_evaluator_id = assigned_evaluator_id
        if assessment_id is not None:
            self.assessment_id = assessment_id
        self.group = group

    @property
    def assigned_evaluator_id(self):
        """Gets the assigned_evaluator_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501

        UserId of the assigned evaluator (for assignment).  # noqa: E501

        :return: The assigned_evaluator_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :rtype: str
        """
        return self._assigned_evaluator_id

    @assigned_evaluator_id.setter
    def assigned_evaluator_id(self, assigned_evaluator_id):
        """Sets the assigned_evaluator_id of this GroupWithAssignedEvaluatorDto.

        UserId of the assigned evaluator (for assignment).  # noqa: E501

        :param assigned_evaluator_id: The assigned_evaluator_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :type: str
        """

        self._assigned_evaluator_id = assigned_evaluator_id

    @property
    def assessment_id(self):
        """Gets the assessment_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501

        Id of the assessment, if it exists.  # noqa: E501

        :return: The assessment_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """Sets the assessment_id of this GroupWithAssignedEvaluatorDto.

        Id of the assessment, if it exists.  # noqa: E501

        :param assessment_id: The assessment_id of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :type: str
        """

        self._assessment_id = assessment_id

    @property
    def group(self):
        """Gets the group of this GroupWithAssignedEvaluatorDto.  # noqa: E501


        :return: The group of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :rtype: GroupDto
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this GroupWithAssignedEvaluatorDto.


        :param group: The group of this GroupWithAssignedEvaluatorDto.  # noqa: E501
        :type: GroupDto
        """
        if group is None:
            raise ValueError("Invalid value for `group`, must not be `None`")  # noqa: E501

        self._group = group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupWithAssignedEvaluatorDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupWithAssignedEvaluatorDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
