# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NotificationDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event': 'str',
        'course_id': 'str',
        'assignment_id': 'str',
        'group_id': 'str',
        'user_id': 'str',
        'payload': 'object'
    }

    attribute_map = {
        'event': 'event',
        'course_id': 'courseId',
        'assignment_id': 'assignmentId',
        'group_id': 'groupId',
        'user_id': 'userId',
        'payload': 'payload'
    }

    def __init__(self, event=None, course_id=None, assignment_id=None, group_id=None, user_id=None, payload=None):  # noqa: E501
        """NotificationDto - a model defined in Swagger"""  # noqa: E501
        self._event = None
        self._course_id = None
        self._assignment_id = None
        self._group_id = None
        self._user_id = None
        self._payload = None
        self.discriminator = None
        self.event = event
        self.course_id = course_id
        if assignment_id is not None:
            self.assignment_id = assignment_id
        if group_id is not None:
            self.group_id = group_id
        if user_id is not None:
            self.user_id = user_id
        if payload is not None:
            self.payload = payload

    @property
    def event(self):
        """Gets the event of this NotificationDto.  # noqa: E501


        :return: The event of this NotificationDto.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this NotificationDto.


        :param event: The event of this NotificationDto.  # noqa: E501
        :type: str
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501
        allowed_values = ["COURSE_JOINED", "ASSIGNMENT_CREATED", "ASSIGNMENT_UPDATED", "ASSIGNMENT_REMOVED", "ASSIGNMENT_STATE_CHANGED", "GROUP_REGISTERED", "GROUP_UNREGISTERED", "USER_REGISTERED", "USER_UNREGISTERED", "USER_JOINED_GROUP", "USER_LEFT_GROUP", "REGISTRATIONS_CREATED", "REGISTRATIONS_REMOVED"]  # noqa: E501
        if event not in allowed_values:
            raise ValueError(
                "Invalid value for `event` ({0}), must be one of {1}"  # noqa: E501
                .format(event, allowed_values)
            )

        self._event = event

    @property
    def course_id(self):
        """Gets the course_id of this NotificationDto.  # noqa: E501


        :return: The course_id of this NotificationDto.  # noqa: E501
        :rtype: str
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id):
        """Sets the course_id of this NotificationDto.


        :param course_id: The course_id of this NotificationDto.  # noqa: E501
        :type: str
        """
        if course_id is None:
            raise ValueError("Invalid value for `course_id`, must not be `None`")  # noqa: E501

        self._course_id = course_id

    @property
    def assignment_id(self):
        """Gets the assignment_id of this NotificationDto.  # noqa: E501


        :return: The assignment_id of this NotificationDto.  # noqa: E501
        :rtype: str
        """
        return self._assignment_id

    @assignment_id.setter
    def assignment_id(self, assignment_id):
        """Sets the assignment_id of this NotificationDto.


        :param assignment_id: The assignment_id of this NotificationDto.  # noqa: E501
        :type: str
        """

        self._assignment_id = assignment_id

    @property
    def group_id(self):
        """Gets the group_id of this NotificationDto.  # noqa: E501


        :return: The group_id of this NotificationDto.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this NotificationDto.


        :param group_id: The group_id of this NotificationDto.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def user_id(self):
        """Gets the user_id of this NotificationDto.  # noqa: E501


        :return: The user_id of this NotificationDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this NotificationDto.


        :param user_id: The user_id of this NotificationDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def payload(self):
        """Gets the payload of this NotificationDto.  # noqa: E501


        :return: The payload of this NotificationDto.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this NotificationDto.


        :param payload: The payload of this NotificationDto.  # noqa: E501
        :type: object
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NotificationDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
