# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PointsOverviewDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assignments': 'list[AssignmentDto]',
        'results': 'list[StudentResults]'
    }

    attribute_map = {
        'assignments': 'assignments',
        'results': 'results'
    }

    def __init__(self, assignments=None, results=None):  # noqa: E501
        """PointsOverviewDto - a model defined in Swagger"""  # noqa: E501
        self._assignments = None
        self._results = None
        self.discriminator = None
        self.assignments = assignments
        self.results = results

    @property
    def assignments(self):
        """Gets the assignments of this PointsOverviewDto.  # noqa: E501


        :return: The assignments of this PointsOverviewDto.  # noqa: E501
        :rtype: list[AssignmentDto]
        """
        return self._assignments

    @assignments.setter
    def assignments(self, assignments):
        """Sets the assignments of this PointsOverviewDto.


        :param assignments: The assignments of this PointsOverviewDto.  # noqa: E501
        :type: list[AssignmentDto]
        """
        if assignments is None:
            raise ValueError("Invalid value for `assignments`, must not be `None`")  # noqa: E501

        self._assignments = assignments

    @property
    def results(self):
        """Gets the results of this PointsOverviewDto.  # noqa: E501


        :return: The results of this PointsOverviewDto.  # noqa: E501
        :rtype: list[StudentResults]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this PointsOverviewDto.


        :param results: The results of this PointsOverviewDto.  # noqa: E501
        :type: list[StudentResults]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PointsOverviewDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PointsOverviewDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
