# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RExportUserInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'username': 'str',
        'display_name': 'str',
        'matr_nr': 'float'
    }

    attribute_map = {
        'user_id': 'userId',
        'username': 'username',
        'display_name': 'displayName',
        'matr_nr': 'matrNr'
    }

    def __init__(self, user_id=None, username=None, display_name=None, matr_nr=None):  # noqa: E501
        """RExportUserInfo - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._username = None
        self._display_name = None
        self._matr_nr = None
        self.discriminator = None
        self.user_id = user_id
        self.username = username
        self.display_name = display_name
        if matr_nr is not None:
            self.matr_nr = matr_nr

    @property
    def user_id(self):
        """Gets the user_id of this RExportUserInfo.  # noqa: E501


        :return: The user_id of this RExportUserInfo.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this RExportUserInfo.


        :param user_id: The user_id of this RExportUserInfo.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def username(self):
        """Gets the username of this RExportUserInfo.  # noqa: E501


        :return: The username of this RExportUserInfo.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this RExportUserInfo.


        :param username: The username of this RExportUserInfo.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def display_name(self):
        """Gets the display_name of this RExportUserInfo.  # noqa: E501


        :return: The display_name of this RExportUserInfo.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this RExportUserInfo.


        :param display_name: The display_name of this RExportUserInfo.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def matr_nr(self):
        """Gets the matr_nr of this RExportUserInfo.  # noqa: E501


        :return: The matr_nr of this RExportUserInfo.  # noqa: E501
        :rtype: float
        """
        return self._matr_nr

    @matr_nr.setter
    def matr_nr(self, matr_nr):
        """Sets the matr_nr of this RExportUserInfo.


        :param matr_nr: The matr_nr of this RExportUserInfo.  # noqa: E501
        :type: float
        """

        self._matr_nr = matr_nr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RExportUserInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RExportUserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
