# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RExportGrade(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assignment_id': 'str',
        'assessment_id': 'str',
        'assignment_type': 'str',
        'achieved_points_in_percent': 'float',
        'group': 'GroupDto'
    }

    attribute_map = {
        'assignment_id': 'assignmentId',
        'assessment_id': 'assessmentId',
        'assignment_type': 'assignmentType',
        'achieved_points_in_percent': 'achievedPointsInPercent',
        'group': 'group'
    }

    def __init__(self, assignment_id=None, assessment_id=None, assignment_type=None, achieved_points_in_percent=None, group=None):  # noqa: E501
        """RExportGrade - a model defined in Swagger"""  # noqa: E501
        self._assignment_id = None
        self._assessment_id = None
        self._assignment_type = None
        self._achieved_points_in_percent = None
        self._group = None
        self.discriminator = None
        self.assignment_id = assignment_id
        self.assessment_id = assessment_id
        self.assignment_type = assignment_type
        self.achieved_points_in_percent = achieved_points_in_percent
        if group is not None:
            self.group = group

    @property
    def assignment_id(self):
        """Gets the assignment_id of this RExportGrade.  # noqa: E501


        :return: The assignment_id of this RExportGrade.  # noqa: E501
        :rtype: str
        """
        return self._assignment_id

    @assignment_id.setter
    def assignment_id(self, assignment_id):
        """Sets the assignment_id of this RExportGrade.


        :param assignment_id: The assignment_id of this RExportGrade.  # noqa: E501
        :type: str
        """
        if assignment_id is None:
            raise ValueError("Invalid value for `assignment_id`, must not be `None`")  # noqa: E501

        self._assignment_id = assignment_id

    @property
    def assessment_id(self):
        """Gets the assessment_id of this RExportGrade.  # noqa: E501


        :return: The assessment_id of this RExportGrade.  # noqa: E501
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """Sets the assessment_id of this RExportGrade.


        :param assessment_id: The assessment_id of this RExportGrade.  # noqa: E501
        :type: str
        """
        if assessment_id is None:
            raise ValueError("Invalid value for `assessment_id`, must not be `None`")  # noqa: E501

        self._assessment_id = assessment_id

    @property
    def assignment_type(self):
        """Gets the assignment_type of this RExportGrade.  # noqa: E501


        :return: The assignment_type of this RExportGrade.  # noqa: E501
        :rtype: str
        """
        return self._assignment_type

    @assignment_type.setter
    def assignment_type(self, assignment_type):
        """Sets the assignment_type of this RExportGrade.


        :param assignment_type: The assignment_type of this RExportGrade.  # noqa: E501
        :type: str
        """
        if assignment_type is None:
            raise ValueError("Invalid value for `assignment_type`, must not be `None`")  # noqa: E501
        allowed_values = ["HOMEWORK", "TESTAT", "SEMINAR", "PROJECT", "OTHER"]  # noqa: E501
        if assignment_type not in allowed_values:
            raise ValueError(
                "Invalid value for `assignment_type` ({0}), must be one of {1}"  # noqa: E501
                .format(assignment_type, allowed_values)
            )

        self._assignment_type = assignment_type

    @property
    def achieved_points_in_percent(self):
        """Gets the achieved_points_in_percent of this RExportGrade.  # noqa: E501


        :return: The achieved_points_in_percent of this RExportGrade.  # noqa: E501
        :rtype: float
        """
        return self._achieved_points_in_percent

    @achieved_points_in_percent.setter
    def achieved_points_in_percent(self, achieved_points_in_percent):
        """Sets the achieved_points_in_percent of this RExportGrade.


        :param achieved_points_in_percent: The achieved_points_in_percent of this RExportGrade.  # noqa: E501
        :type: float
        """
        if achieved_points_in_percent is None:
            raise ValueError("Invalid value for `achieved_points_in_percent`, must not be `None`")  # noqa: E501

        self._achieved_points_in_percent = achieved_points_in_percent

    @property
    def group(self):
        """Gets the group of this RExportGrade.  # noqa: E501


        :return: The group of this RExportGrade.  # noqa: E501
        :rtype: GroupDto
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this RExportGrade.


        :param group: The group of this RExportGrade.  # noqa: E501
        :type: GroupDto
        """

        self._group = group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RExportGrade, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RExportGrade):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
