# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubmissionDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assignment_id': 'str',
        'user_id': 'str',
        'display_name': 'str',
        '_date': 'datetime',
        'group_id': 'str',
        'group_name': 'str',
        'links': 'list[LinkDto]',
        'payload': 'object'
    }

    attribute_map = {
        'assignment_id': 'assignmentId',
        'user_id': 'userId',
        'display_name': 'displayName',
        '_date': 'date',
        'group_id': 'groupId',
        'group_name': 'groupName',
        'links': 'links',
        'payload': 'payload'
    }

    def __init__(self, assignment_id=None, user_id=None, display_name=None, _date=None, group_id=None, group_name=None, links=None, payload=None):  # noqa: E501
        """SubmissionDto - a model defined in Swagger"""  # noqa: E501
        self._assignment_id = None
        self._user_id = None
        self._display_name = None
        self.__date = None
        self._group_id = None
        self._group_name = None
        self._links = None
        self._payload = None
        self.discriminator = None
        self.assignment_id = assignment_id
        self.user_id = user_id
        self.display_name = display_name
        self._date = _date
        if group_id is not None:
            self.group_id = group_id
        if group_name is not None:
            self.group_name = group_name
        if links is not None:
            self.links = links
        if payload is not None:
            self.payload = payload

    @property
    def assignment_id(self):
        """Gets the assignment_id of this SubmissionDto.  # noqa: E501


        :return: The assignment_id of this SubmissionDto.  # noqa: E501
        :rtype: str
        """
        return self._assignment_id

    @assignment_id.setter
    def assignment_id(self, assignment_id):
        """Sets the assignment_id of this SubmissionDto.


        :param assignment_id: The assignment_id of this SubmissionDto.  # noqa: E501
        :type: str
        """
        if assignment_id is None:
            raise ValueError("Invalid value for `assignment_id`, must not be `None`")  # noqa: E501

        self._assignment_id = assignment_id

    @property
    def user_id(self):
        """Gets the user_id of this SubmissionDto.  # noqa: E501


        :return: The user_id of this SubmissionDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SubmissionDto.


        :param user_id: The user_id of this SubmissionDto.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def display_name(self):
        """Gets the display_name of this SubmissionDto.  # noqa: E501


        :return: The display_name of this SubmissionDto.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this SubmissionDto.


        :param display_name: The display_name of this SubmissionDto.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def _date(self):
        """Gets the _date of this SubmissionDto.  # noqa: E501


        :return: The _date of this SubmissionDto.  # noqa: E501
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this SubmissionDto.


        :param _date: The _date of this SubmissionDto.  # noqa: E501
        :type: datetime
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def group_id(self):
        """Gets the group_id of this SubmissionDto.  # noqa: E501


        :return: The group_id of this SubmissionDto.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this SubmissionDto.


        :param group_id: The group_id of this SubmissionDto.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def group_name(self):
        """Gets the group_name of this SubmissionDto.  # noqa: E501


        :return: The group_name of this SubmissionDto.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this SubmissionDto.


        :param group_name: The group_name of this SubmissionDto.  # noqa: E501
        :type: str
        """

        self._group_name = group_name

    @property
    def links(self):
        """Gets the links of this SubmissionDto.  # noqa: E501


        :return: The links of this SubmissionDto.  # noqa: E501
        :rtype: list[LinkDto]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SubmissionDto.


        :param links: The links of this SubmissionDto.  # noqa: E501
        :type: list[LinkDto]
        """

        self._links = links

    @property
    def payload(self):
        """Gets the payload of this SubmissionDto.  # noqa: E501


        :return: The payload of this SubmissionDto.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this SubmissionDto.


        :param payload: The payload of this SubmissionDto.  # noqa: E501
        :type: object
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmissionDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmissionDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
