# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SubmissionCreateDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'group_id': 'str',
        'links': 'list[LinkDto]',
        'payload': 'object'
    }

    attribute_map = {
        'user_id': 'userId',
        'group_id': 'groupId',
        'links': 'links',
        'payload': 'payload'
    }

    def __init__(self, user_id=None, group_id=None, links=None, payload=None):  # noqa: E501
        """SubmissionCreateDto - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._group_id = None
        self._links = None
        self._payload = None
        self.discriminator = None
        self.user_id = user_id
        if group_id is not None:
            self.group_id = group_id
        if links is not None:
            self.links = links
        if payload is not None:
            self.payload = payload

    @property
    def user_id(self):
        """Gets the user_id of this SubmissionCreateDto.  # noqa: E501


        :return: The user_id of this SubmissionCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SubmissionCreateDto.


        :param user_id: The user_id of this SubmissionCreateDto.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def group_id(self):
        """Gets the group_id of this SubmissionCreateDto.  # noqa: E501


        :return: The group_id of this SubmissionCreateDto.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this SubmissionCreateDto.


        :param group_id: The group_id of this SubmissionCreateDto.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def links(self):
        """Gets the links of this SubmissionCreateDto.  # noqa: E501


        :return: The links of this SubmissionCreateDto.  # noqa: E501
        :rtype: list[LinkDto]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SubmissionCreateDto.


        :param links: The links of this SubmissionCreateDto.  # noqa: E501
        :type: list[LinkDto]
        """

        self._links = links

    @property
    def payload(self):
        """Gets the payload of this SubmissionCreateDto.  # noqa: E501


        :return: The payload of this SubmissionCreateDto.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this SubmissionCreateDto.


        :param payload: The payload of this SubmissionCreateDto.  # noqa: E501
        :type: object
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubmissionCreateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmissionCreateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
