# coding: utf-8

"""
    Student-Management-System-API

    The Student-Management-System-API. <a href='http://147.172.178.30:8080/stmgmt/api-json'>JSON</a>  # noqa: E501

    OpenAPI spec version: 2.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'role': 'str',
        'matr_nr': 'float',
        'email': 'str',
        'username': 'str',
        'display_name': 'str',
        'courses': 'list[CourseDto]'
    }

    attribute_map = {
        'id': 'id',
        'role': 'role',
        'matr_nr': 'matrNr',
        'email': 'email',
        'username': 'username',
        'display_name': 'displayName',
        'courses': 'courses'
    }

    def __init__(self, id=None, role=None, matr_nr=None, email=None, username=None, display_name=None, courses=None):  # noqa: E501
        """UserDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._role = None
        self._matr_nr = None
        self._email = None
        self._username = None
        self._display_name = None
        self._courses = None
        self.discriminator = None
        self.id = id
        self.role = role
        if matr_nr is not None:
            self.matr_nr = matr_nr
        if email is not None:
            self.email = email
        self.username = username
        self.display_name = display_name
        if courses is not None:
            self.courses = courses

    @property
    def id(self):
        """Gets the id of this UserDto.  # noqa: E501

        Unique identifier of this user.  # noqa: E501

        :return: The id of this UserDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserDto.

        Unique identifier of this user.  # noqa: E501

        :param id: The id of this UserDto.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def role(self):
        """Gets the role of this UserDto.  # noqa: E501

        Role within the application.  # noqa: E501

        :return: The role of this UserDto.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this UserDto.

        Role within the application.  # noqa: E501

        :param role: The role of this UserDto.  # noqa: E501
        :type: str
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501
        allowed_values = ["SYSTEM_ADMIN", "ADMIN_TOOL", "MGMT_ADMIN", "USER"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"  # noqa: E501
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def matr_nr(self):
        """Gets the matr_nr of this UserDto.  # noqa: E501


        :return: The matr_nr of this UserDto.  # noqa: E501
        :rtype: float
        """
        return self._matr_nr

    @matr_nr.setter
    def matr_nr(self, matr_nr):
        """Sets the matr_nr of this UserDto.


        :param matr_nr: The matr_nr of this UserDto.  # noqa: E501
        :type: float
        """

        self._matr_nr = matr_nr

    @property
    def email(self):
        """Gets the email of this UserDto.  # noqa: E501


        :return: The email of this UserDto.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserDto.


        :param email: The email of this UserDto.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def username(self):
        """Gets the username of this UserDto.  # noqa: E501


        :return: The username of this UserDto.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserDto.


        :param username: The username of this UserDto.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def display_name(self):
        """Gets the display_name of this UserDto.  # noqa: E501


        :return: The display_name of this UserDto.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this UserDto.


        :param display_name: The display_name of this UserDto.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def courses(self):
        """Gets the courses of this UserDto.  # noqa: E501


        :return: The courses of this UserDto.  # noqa: E501
        :rtype: list[CourseDto]
        """
        return self._courses

    @courses.setter
    def courses(self, courses):
        """Sets the courses of this UserDto.


        :param courses: The courses of this UserDto.  # noqa: E501
        :type: list[CourseDto]
        """

        self._courses = courses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
